CREATE DATABASE HIPOTECA;

CREATE USER 'hipoteco'@'localhost' IDENTIFIED BY 'Ageofempires2'; 

GRANT SELECT, INSERT, DELETE, UPDATE ON HIPOTECA.* TO 'hipoteco'@'localhost';

USE HIPOTECA;

CREATE TABLE USUARIO(
ID INT NOT NULL auto_increment,
NOMBRE VARCHAR(50) NOT NULL,
USUARIO VARCHAR(50) NOT NULL,
PASS VARCHAR(50) NOT NULL,
NOMBRE_FOTO VARCHAR(50) NOT NULL,

PRIMARY KEY(ID)
 
);

CREATE TABLE SIMULACION(
ID INT NOT NULL AUTO_INCREMENT,
CAPITAL double NOT NULL,
INTERES INT NOT NULL,
MES INT NOT NULL,
ID_USUARIO INT NOT NULL,
CUADRO_AMORTIZACION INT NOT NULL,

PRIMARY KEY (ID),
FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID)

);

INSERT INTO USUARIO(NOMBRE, USUARIO, PASS, NOMBRE_FOTO) VALUES("IBAN","JIMENEZ","PASSWOR","POALGO"),("IBAN2","JIMENEZ2","PASSWOR","POALGO"),("IBAN3","JIMENEZ3","PASSWOR","POALGO")
;

INSERT INTO USUARIO(NOMBRE, USUARIO, PASS, NOMBRE_FOTO) VALUES("ivan","ivan","pass","POALGO");
INSERT INTO USUARIO(NOMBRE, USUARIO, PASS, NOMBRE_FOTO) VALUES("tomas","tomas","patata23","POALGO");


INSERT INTO SIMULACION(CAPITAL, INTERES, MES, ID_USUARIO, CUADRO_AMORTIZACION) VALUES(200000.0,3,15,1,1);
INSERT INTO SIMULACION(CAPITAL, INTERES, MES, ID_USUARIO, CUADRO_AMORTIZACION) VALUES(400000.0,5,2,2,0);
INSERT INTO SIMULACION(CAPITAL, INTERES, MES, ID_USUARIO, CUADRO_AMORTIZACION) VALUES(300000.0,14,60,3,0);
INSERT INTO SIMULACION(CAPITAL, INTERES, MES, ID_USUARIO, CUADRO_AMORTIZACION) VALUES(205000.0,1,60,1,1);
INSERT INTO SIMULACION(CAPITAL, INTERES, MES, ID_USUARIO, CUADRO_AMORTIZACION) VALUES(200000.0,2,60,2,0);
INSERT INTO SIMULACION(CAPITAL, INTERES, MES, ID_USUARIO, CUADRO_AMORTIZACION) VALUES(202000.0,3,760,3,1);
INSERT INTO SIMULACION(CAPITAL, INTERES, MES, ID_USUARIO, CUADRO_AMORTIZACION) VALUES(600000.0,8,60,1,0);
INSERT INTO SIMULACION(CAPITAL, INTERES, MES, ID_USUARIO, CUADRO_AMORTIZACION) VALUES(500000.0,3,60,2,1);




