CREATE DATABASE HIPOTECA;

CREATE USER 'hipoteco'@'localhost' IDENTIFIED BY 'Ageofempires2'; 

GRANT SELECT, INSERT, DELETE, UPDATE ON HIPOTECA.* TO 'hipoteco'@'localhost';

USE HIPOTECA;

CREATE TABLE USUARIO(
ID INT NOT NULL auto_increment,
NOMBRE VARCHAR(50) NOT NULL,
USUARIO VARCHAR(50) NOT NULL,
PASS VARCHAR(50) NOT NULL,
NOMBRE_FOTO VARCHAR(50) NOT NULL,

PRIMARY KEY(ID)
 
);

CREATE TABLE SIMULACION(
ID INT NOT NULL AUTO_INCREMENT,
CAPITAL int NOT NULL,
INTERES INT NOT NULL,
ANYOS INT NOT NULL,
ID_USUARIO INT NOT NULL,
CUADRO_AMORTIZACION INT NOT NULL,

PRIMARY KEY (ID),
FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID)

);

INSERT INTO USUARIO(NOMBRE, USUARIO, PASS, NOMBRE_FOTO) VALUES("IBAN","JIMENEZ","PASSWOR","POALGO"),("IBAN2","JIMENEZ2","PASSWOR","POALGO"),("IBAN3","JIMENEZ3","PASSWOR","POALGO")
;
SELECT * FROM USUARIO;

