CREATE DATABASE GAMELAND;
USE GAMELAND;

CREATE USER 'gamelandIvan'@'localhost' IDENTIFIED BY 'Ageofempires2'; 

GRANT SELECT, INSERT, DELETE, UPDATE ON GAMELAND.* TO 'gamelandIvan'@'localhost';

CREATE TABLE PLATAFORMA(
ID INT(11) NOT NULL auto_increment,
NOMBRE varchar(100) NOT NULL,

primary key (ID)

);

INSERT INTO PLATAFORMA(NOMBRE) VALUES("PS4"),("XBOX"),("SWITCH"),("PC");

CREATE TABLE GENERO(
ID INT(11) NOT NULL auto_increment,
NOMBRE varchar(100) NOT NULL,

primary key (ID)


);
INSERT INTO GENERO(NOMBRE) VALUES("SHOOTER"),("DEPORTE"),("ESTRATEGIA"),("PUZZLE");


CREATE TABLE JUEGO(
ID INT(11) NOT NULL auto_increment,
TITULO varchar(100) NOT NULL,
ANYO INT NOT NULL,
FOTO VARCHAR(255),
DESCRIPCION VARCHAR(255),
IDGENERO INT(11) NOT NULL,
IDPLATAFORMA INT(11) NOT NULL,

primary key(ID),
foreign key(IDGENERO) references GENERO(ID),
foreign key(IDPLATAFORMA) references PLATAFORMA(ID)

);

INSERT INTO JUEGO(TITULO, ANYO, FOTO, DESCRIPCION, IDGENERO, IDPLATAFORMA) 
VALUES("CALL OF DUTY", 2011, "PRUEBA", "CARLOS DUTY EL JUEGO DE DISPAROS", 1, 1)
,("FIFA", 2014, "PRUEBA", "DOÑA ASEME EL CORTE DE SERRESIETE", 2,2 )
,("AGE OF EMPIRES 2", 2004, "PRUEBA", "ELEFANTES TAL ETC", 3,3 )
,("PROFESOR LAYTON", 2019, "PRUEBA", "TIENE 2000 DE IQ", 4,4 );

INSERT INTO JUEGO(TITULO, ANYO, FOTO, DESCRIPCION, IDGENERO, IDPLATAFORMA) VALUES("LO IMPERIO 2", 2007, "PRUEBA", "ELEFANTES TAL ETC", 3,1 ), 
("LO IMPERIO 3", 2007, "PRUEBA", "ELEFANTES TAL ETC", 3,2 ),
("XDDD EL VIDEOJUEGO", 2007, "PRUEBA", "ELEFANTES TAL ETC", 3,1 ), 
("TEST1", 2007, "PRUEBA", "ELEFANTES TAL ETC", 3,1 ),
("TEST2", 2007, "PRUEBA", "ELEFANTES TAL ETC", 3,3 ),
("TEST3", 2007, "PRUEBA", "ELEFANTES TAL ETC", 3,2 ),
("TEST4", 2007, "PRUEBA", "ELEFANTES TAL ETC", 3,4 )
,("TEST5", 2007, "PRUEBA", "ELEFANTES TAL ETC", 1,1 ),
("TEST6", 2007, "PRUEBA", "ELEFANTES TAL ETC", 1,3 ),
("TEST7", 2007, "PRUEBA", "ELEFANTES TAL ETC", 1,2 ),
("TEST8", 2007, "PRUEBA", "ELEFANTES TAL ETC", 1,4 ),
("TEST9", 2007, "PRUEBA", "ELEFANTES TAL ETC", 2,1 ),
("TEST10", 2007, "PRUEBA", "ELEFANTES TAL ETC", 2,3 ),
("TEST11", 2007, "PRUEBA", "ELEFANTES TAL ETC", 2,2 ),
("TEST12", 2007, "PRUEBA", "ELEFANTES TAL ETC", 2,4 ),
("TEST13", 2007, "PRUEBA", "ELEFANTES TAL ETC", 3,1 ),
("TEST14", 2007, "PRUEBA", "ELEFANTES TAL ETC", 3,3 ),
("TEST15", 2007, "PRUEBA", "ELEFANTES TAL ETC", 3,2 ),
("TEST16", 2007, "PRUEBA", "ELEFANTES TAL ETC", 3,4 ),
("TEST17", 2007, "PRUEBA", "ELEFANTES TAL ETC", 4,1 ),
("TEST18", 2007, "PRUEBA", "ELEFANTES TAL ETC", 4,3 ),
("TEST19", 2007, "PRUEBA", "ELEFANTES TAL ETC", 4,2 ),
("TEST20", 2007, "PRUEBA", "ELEFANTES TAL ETC", 4,4 );

CREATE TABLE USUARIO(
ID INT(11) NOT NULL auto_increment,
NOMBRE VARCHAR(100) NOT NULL,
USUARIO VARCHAR(100) NOT NULL,
PASS VARCHAR(100) NOT NULL,
FOTO VARCHAR(100) NOT NULL,
ADMINISTRADOR INT(1) NOT NULL,

primary key(ID)


);

INSERT INTO USUARIO(NOMBRE, USUARIO, PASS, FOTO, ADMINISTRADOR) VALUES("ivanTest1","xenoteckTest1", "123", "test1", 0),
("ivanTest2","xenoteckTest2", "123", "test2", 0),
("ivanTest3","xenoteckTest3", "123", "test3", 0),
("ivanTest4","xenoteckTest4", "123", "test4", 0);
INSERT INTO USUARIO(NOMBRE, USUARIO, PASS, FOTO, ADMINISTRADOR) VALUES("admin","admin", "123", "test1", 1);


CREATE TABLE VALORACION(
ID INT(11) NOT NULL auto_increment,
IDJUEGO INT(11) NOT NULL,
IDUSUARIO INT(11) NOT NULL,
VALORACION INT(11) NOT NULL,

primary key(ID),

FOREIGN KEY (IDJUEGO) references JUEGO(ID),
FOREIGN KEY (IDUSUARIO) references USUARIO(ID)
);


INSERT INTO VALORACION(IDJUEGO, IDUSUARIO, VALORACION) VALUES(1,1,4),(2,1,3),(3,1,1),(4,1,5);
INSERT INTO VALORACION(IDJUEGO, IDUSUARIO, VALORACION) VALUES(9,1,4),(10,1,3),(11,1,1),(12,1,5);


INSERT INTO VALORACION(IDJUEGO, IDUSUARIO, VALORACION) VALUES(17,1,4),(18,1,3),(19,1,1),(20,2,3);
