CREATE DATABASE MYBATIS;
USE MYBATIS;

CREATE USER 'batisivan'@'localhost' IDENTIFIED BY 'Ageofempires2';
GRANT SELECT, INSERT, DELETE, UPDATE ON MYBATIS.* TO 'batisivan'@'localhost';

CREATE TABLE EQUIPO(
ID INT NOT NULL auto_increment,
NOMBRE VARCHAR(50) NOT NULL,

primary key(ID)

);

INSERT INTO EQUIPO(NOMBRE) VALUES("BETI"), ("BCN"), ("GAMERS"); 

CREATE TABLE USUARIO(
ID INT NOT NULL auto_increment,
NOMBRE VARCHAR(30) NOT NULL,

ID_EQUIPO INT NOT NULL,

PRIMARY KEY(ID),
foreign key(ID_EQUIPO) REFERENCES EQUIPO(ID)

);

INSERT INTO USUARIO(NOMBRE, ID_EQUIPO) VALUES("GOKU", 1), ("LOCOPIZZA",2), ("ESPAÑOL", 3);
INSERT INTO USUARIO(NOMBRE, ID_EQUIPO) VALUES("GOKU2", 1), ("LOCOPIZZA2",2), ("ESPAÑOL2", 3);
INSERT INTO USUARIO(NOMBRE, ID_EQUIPO) VALUES("GOKU3", 1), ("LOCOPIZZA3",2), ("ESPAÑOL3", 3);

